ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'LEVEL_A1';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'LEVEL_A2';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'LEVEL_B1';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'LEVEL_B2';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'LEVEL_C1';
